apiVersion: v1
data:
  DB_NAME: bnVyX2FsX3F1cmFu
  DB_PASSWORD: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  JWT_SECRET: NDU5YjkxMmMzNDJiZGNkMzNlMGVkZmM0YjIxNzI1YmQ5OTlmYjg1M2QxZDU1ZjMwZTg3ZmQ2MWI5YjQzMWU3Mw==
kind: Secret
metadata:
  creationTimestamp: "2026-07-09T11:51:47Z"
  name: secret-myapp
  namespace: default
  resourceVersion: "28098"
type: Opaque
