apiVersion: v1
data:
  .env: |
    PORT=4000
    DB_PORT=5432
    FRONTEND_URL=http://aede4cc2b85704a33b5a93283a1922f2-1115593351.us-east-1.elb.amazonaws.com
kind: ConfigMap
metadata:
  name: configmap-myapp
