apiVersion: v1
data:
  .env: |
    PORT=4000
    DB_PORT=5432
    FRONTEND_URL=http://a4b49e1f5656b472aa1d5e235d0d9312-1901052262.us-east-1.elb.amazonaws.com
kind: ConfigMap
metadata:
  name: configmap-myapp
