apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frontend-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
